# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a32215c82dc71a9f8b03713fc3e61d47af7eb10de01c505f65cdbdaa5d040232d3ad7e317c67a476a17ff1525d07b5094fd4d9a6f3249b9991feca3d483572d2

test:
  secret_key_base: a15b8139c9f1aeb310dd5f06be1ea2a01b477d00e9415b1f9902415a019232023b4a55a5727886230bab21e22b6b4628250460b8966d764962ee54cf8a300405

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 8e4e8f0dabf80f5055992d1652bde3b45037fd86a1ee84e98e25b48a26fc144b235e320909ada885226c35249cbedb54878e5f62c7aad45587b6505c674dc285

