Product.create(sku: '1', description: 'Pollo', _type: 'Materia prima', creator: 1, unit: 'Kg', unit_production_cost: 290, batch: 300, ingredients_number: 0, dependents: 1, production_time: 2.176)
Product.create(sku: '1', description: 'Pollo', _type: 'Materia prima', creator: 3, unit: 'Kg', unit_production_cost: 290, batch: 300, ingredients_number: 0, dependents: 1, production_time: 3.605)
Product.create(sku: '2', description: 'Huevo', _type: 'Materia prima', creator: 2, unit: 'Un', unit_production_cost: 102, batch: 150, ingredients_number: 0, dependents: 4, production_time: 2.551)
Product.create(sku: '2', description: 'Huevo', _type: 'Materia prima', creator: 4, unit: 'Un', unit_production_cost: 102, batch: 150, ingredients_number: 0, dependents: 4, production_time: 2.011)
Product.create(sku: '2', description: 'Huevo', _type: 'Materia prima', creator: 6, unit: 'Un', unit_production_cost: 102, batch: 150, ingredients_number: 0, dependents: 4, production_time: 2.375)
Product.create(sku: '3', description: 'Maíz', _type: 'Materia prima', creator: 3, unit: 'Kg', unit_production_cost: 117, batch: 30, ingredients_number: 0, dependents: 1, production_time: 2.172)
Product.create(sku: '3', description: 'Maíz', _type: 'Materia prima', creator: 5, unit: 'Kg', unit_production_cost: 117, batch: 30, ingredients_number: 0, dependents: 1, production_time: 1.726)
Product.create(sku: '4', description: 'Aceite de Maravilla', _type: 'Producto procesado', creator: 4, unit: 'Lts', unit_production_cost: 412, batch: 200, ingredients_number: 1, dependents: 2, production_time: 2.713)
Product.create(sku: '4', description: 'Aceite de Maravilla', _type: 'Producto procesado', creator: 6, unit: 'Lts', unit_production_cost: 412, batch: 200, ingredients_number: 1, dependents: 2, production_time: 2.615)
Product.create(sku: '4', description: 'Aceite de Maravilla', _type: 'Producto procesado', creator: 8, unit: 'Lts', unit_production_cost: 412, batch: 200, ingredients_number: 1, dependents: 2, production_time: 1.205)
Product.create(sku: '5', description: 'Yogur ', _type: 'Producto procesado', creator: 5, unit: 'Lts', unit_production_cost: 428, batch: 600, ingredients_number: 3, dependents: 0, production_time: 3.191)
Product.create(sku: '6', description: 'Crema', _type: 'Producto procesado', creator: 6, unit: 'Lts', unit_production_cost: 514, batch: 30, ingredients_number: 2, dependents: 2, production_time: 2.916)
Product.create(sku: '6', description: 'Crema', _type: 'Producto procesado', creator: 8, unit: 'Lts', unit_production_cost: 514, batch: 30, ingredients_number: 2, dependents: 2, production_time: 2.481)
Product.create(sku: '6', description: 'Crema', _type: 'Producto procesado', creator: 2, unit: 'Lts', unit_production_cost: 514, batch: 30, ingredients_number: 2, dependents: 2, production_time: 2.123)
Product.create(sku: '7', description: 'Leche', _type: 'Materia prima', creator: 1, unit: 'Lts', unit_production_cost: 290, batch: 1000, ingredients_number: 0, dependents: 8, production_time: 1.593)
Product.create(sku: '7', description: 'Leche', _type: 'Materia prima', creator: 3, unit: 'Lts', unit_production_cost: 290, batch: 1000, ingredients_number: 0, dependents: 8, production_time: 2.215)
Product.create(sku: '7', description: 'Leche', _type: 'Materia prima', creator: 5, unit: 'Lts', unit_production_cost: 290, batch: 1000, ingredients_number: 0, dependents: 8, production_time: 1.441)
Product.create(sku: '7', description: 'Leche', _type: 'Materia prima', creator: 7, unit: 'Lts', unit_production_cost: 290, batch: 1000, ingredients_number: 0, dependents: 8, production_time: 3.261)
Product.create(sku: '8', description: 'Trigo', _type: 'Materia prima', creator: 2, unit: 'Kg', unit_production_cost: 252, batch: 100, ingredients_number: 0, dependents: 2, production_time: 1.516)
Product.create(sku: '8', description: 'Trigo', _type: 'Materia prima', creator: 4, unit: 'Kg', unit_production_cost: 252, batch: 100, ingredients_number: 0, dependents: 2, production_time: 2.531)
Product.create(sku: '8', description: 'Trigo', _type: 'Materia prima', creator: 6, unit: 'Kg', unit_production_cost: 252, batch: 100, ingredients_number: 0, dependents: 2, production_time: 3.773)
Product.create(sku: '9', description: 'Carne', _type: 'Materia prima', creator: 3, unit: 'Kg', unit_production_cost: 350, batch: 620, ingredients_number: 0, dependents: 1, production_time: 1.71)
Product.create(sku: '9', description: 'Carne', _type: 'Materia prima', creator: 5, unit: 'Kg', unit_production_cost: 350, batch: 620, ingredients_number: 0, dependents: 1, production_time: 2.846)
Product.create(sku: '10', description: 'Pan Marraqueta', _type: 'Producto procesado', creator: 4, unit: 'Kg', unit_production_cost: 1084, batch: 900, ingredients_number: 4, dependents: 0, production_time: 2.771)
Product.create(sku: '11', description: 'Margarina ', _type: 'Producto procesado', creator: 5, unit: 'Kg', unit_production_cost: 247, batch: 900, ingredients_number: 1, dependents: 0, production_time: 3.074)
Product.create(sku: '12', description: 'Cereal Avena ', _type: 'Producto procesado', creator: 6, unit: 'Kg', unit_production_cost: 624, batch: 400, ingredients_number: 3, dependents: 0, production_time: 3.623)
Product.create(sku: '13', description: 'Arroz', _type: 'Materia prima', creator: 7, unit: 'Kg', unit_production_cost: 358, batch: 1000, ingredients_number: 0, dependents: 2, production_time: 1.304)
Product.create(sku: '13', description: 'Arroz', _type: 'Materia prima', creator: 1, unit: 'Kg', unit_production_cost: 358, batch: 1000, ingredients_number: 0, dependents: 2, production_time: 3.256)
Product.create(sku: '13', description: 'Arroz', _type: 'Materia prima', creator: 3, unit: 'Kg', unit_production_cost: 358, batch: 1000, ingredients_number: 0, dependents: 2, production_time: 3.164)
Product.create(sku: '14', description: 'Cebada', _type: 'Materia prima', creator: 2, unit: 'Kg', unit_production_cost: 296, batch: 1750, ingredients_number: 0, dependents: 1, production_time: 1.816)
Product.create(sku: '14', description: 'Cebada', _type: 'Materia prima', creator: 4, unit: 'Kg', unit_production_cost: 296, batch: 1750, ingredients_number: 0, dependents: 1, production_time: 1.22)
Product.create(sku: '15', description: 'Avena', _type: 'Materia prima', creator: 3, unit: 'Kg', unit_production_cost: 276, batch: 480, ingredients_number: 0, dependents: 1, production_time: 2.669)
Product.create(sku: '15', description: 'Avena', _type: 'Materia prima', creator: 5, unit: 'Kg', unit_production_cost: 276, batch: 480, ingredients_number: 0, dependents: 1, production_time: 1.43)
Product.create(sku: '16', description: 'Pasta de Trigo ', _type: 'Producto procesado', creator: 4, unit: 'Kg', unit_production_cost: 612, batch: 1000, ingredients_number: 3, dependents: 0, production_time: 2.493)
Product.create(sku: '17', description: 'Cereal Arroz ', _type: 'Producto procesado', creator: 5, unit: 'Kg', unit_production_cost: 821, batch: 1000, ingredients_number: 3, dependents: 0, production_time: 1.158)
Product.create(sku: '18', description: 'Pastel ', _type: 'Producto procesado', creator: 6, unit: 'Un', unit_production_cost: 331, batch: 200, ingredients_number: 3, dependents: 0, production_time: 2.48)
Product.create(sku: '19', description: 'Sémola', _type: 'Materia prima', creator: 6, unit: 'Kg', unit_production_cost: 116, batch: 1420, ingredients_number: 0, dependents: 1, production_time: 1.285)
Product.create(sku: '19', description: 'Sémola', _type: 'Materia prima', creator: 8, unit: 'Kg', unit_production_cost: 116, batch: 1420, ingredients_number: 0, dependents: 1, production_time: 1.881)
Product.create(sku: '20', description: 'Cacao', _type: 'Materia prima', creator: 2, unit: 'Kg', unit_production_cost: 172, batch: 60, ingredients_number: 0, dependents: 5, production_time: 3.475)
Product.create(sku: '20', description: 'Cacao', _type: 'Materia prima', creator: 4, unit: 'Kg', unit_production_cost: 172, batch: 60, ingredients_number: 0, dependents: 5, production_time: 1.955)
Product.create(sku: '20', description: 'Cacao', _type: 'Materia prima', creator: 6, unit: 'Kg', unit_production_cost: 172, batch: 60, ingredients_number: 0, dependents: 5, production_time: 3.356)
Product.create(sku: '20', description: 'Cacao', _type: 'Materia prima', creator: 8, unit: 'Kg', unit_production_cost: 172, batch: 60, ingredients_number: 0, dependents: 5, production_time: 2.258)
Product.create(sku: '22', description: 'Mantequilla ', _type: 'Producto procesado', creator: 1, unit: 'Kg', unit_production_cost: 336, batch: 400, ingredients_number: 1, dependents: 1, production_time: 1.283)
Product.create(sku: '22', description: 'Mantequilla ', _type: 'Producto procesado', creator: 3, unit: 'Kg', unit_production_cost: 336, batch: 400, ingredients_number: 1, dependents: 1, production_time: 2.456)
Product.create(sku: '22', description: 'Mantequilla ', _type: 'Producto procesado', creator: 5, unit: 'Kg', unit_production_cost: 336, batch: 400, ingredients_number: 1, dependents: 1, production_time: 1.832)
Product.create(sku: '23', description: 'Harina', _type: 'Producto procesado', creator: 6, unit: 'Kg', unit_production_cost: 364, batch: 300, ingredients_number: 1, dependents: 6, production_time: 1.555)
Product.create(sku: '23', description: 'Harina', _type: 'Producto procesado', creator: 7, unit: 'Kg', unit_production_cost: 364, batch: 300, ingredients_number: 1, dependents: 6, production_time: 1.196)
Product.create(sku: '23', description: 'Harina', _type: 'Producto procesado', creator: 8, unit: 'Kg', unit_production_cost: 364, batch: 300, ingredients_number: 1, dependents: 6, production_time: 0.91)
Product.create(sku: '23', description: 'Harina', _type: 'Producto procesado', creator: 1, unit: 'Kg', unit_production_cost: 364, batch: 300, ingredients_number: 1, dependents: 6, production_time: 2.912)
Product.create(sku: '25', description: 'Azúcar', _type: 'Materia prima', creator: 1, unit: 'Kg', unit_production_cost: 93, batch: 560, ingredients_number: 0, dependents: 6, production_time: 0.821)
Product.create(sku: '25', description: 'Azúcar', _type: 'Materia prima', creator: 3, unit: 'Kg', unit_production_cost: 93, batch: 560, ingredients_number: 0, dependents: 6, production_time: 3.254)
Product.create(sku: '25', description: 'Azúcar', _type: 'Materia prima', creator: 5, unit: 'Kg', unit_production_cost: 93, batch: 560, ingredients_number: 0, dependents: 6, production_time: 2.785)
Product.create(sku: '25', description: 'Azúcar', _type: 'Materia prima', creator: 7, unit: 'Kg', unit_production_cost: 93, batch: 560, ingredients_number: 0, dependents: 6, production_time: 0.945)
Product.create(sku: '26', description: 'Sal', _type: 'Materia prima', creator: 2, unit: 'Kg', unit_production_cost: 99, batch: 144, ingredients_number: 0, dependents: 7, production_time: 2.609)
Product.create(sku: '26', description: 'Sal', _type: 'Materia prima', creator: 4, unit: 'Kg', unit_production_cost: 99, batch: 144, ingredients_number: 0, dependents: 7, production_time: 1.242)
Product.create(sku: '26', description: 'Sal', _type: 'Materia prima', creator: 6, unit: 'Kg', unit_production_cost: 99, batch: 144, ingredients_number: 0, dependents: 7, production_time: 1.092)
Product.create(sku: '26', description: 'Sal', _type: 'Materia prima', creator: 8, unit: 'Kg', unit_production_cost: 99, batch: 144, ingredients_number: 0, dependents: 7, production_time: 3.059)
Product.create(sku: '27', description: 'Levadura', _type: 'Materia prima', creator: 6, unit: 'Kg', unit_production_cost: 232, batch: 620, ingredients_number: 0, dependents: 4, production_time: 3.209)
Product.create(sku: '27', description: 'Levadura', _type: 'Materia prima', creator: 7, unit: 'Kg', unit_production_cost: 232, batch: 620, ingredients_number: 0, dependents: 4, production_time: 3.439)
Product.create(sku: '27', description: 'Levadura', _type: 'Materia prima', creator: 8, unit: 'Kg', unit_production_cost: 232, batch: 620, ingredients_number: 0, dependents: 4, production_time: 1.566)
Product.create(sku: '34', description: 'Cerveza ', _type: 'Producto procesado', creator: 1, unit: 'Lts', unit_production_cost: 557, batch: 700, ingredients_number: 2, dependents: 0, production_time: 1.626)
Product.create(sku: '38', description: 'Semillas Maravilla', _type: 'Materia prima', creator: 7, unit: 'Kg', unit_production_cost: 379, batch: 30, ingredients_number: 0, dependents: 3, production_time: 3.128)
Product.create(sku: '38', description: 'Semillas Maravilla', _type: 'Materia prima', creator: 8, unit: 'Kg', unit_production_cost: 379, batch: 30, ingredients_number: 0, dependents: 3, production_time: 3.462)
Product.create(sku: '39', description: 'Uva', _type: 'Materia prima', creator: 1, unit: 'Kg', unit_production_cost: 233, batch: 250, ingredients_number: 0, dependents: 1, production_time: 3.159)
Product.create(sku: '39', description: 'Uva', _type: 'Materia prima', creator: 2, unit: 'Kg', unit_production_cost: 233, batch: 250, ingredients_number: 0, dependents: 1, production_time: 3.331)
Product.create(sku: '40', description: 'Queso ', _type: 'Producto procesado', creator: 2, unit: 'Kg', unit_production_cost: 596, batch: 900, ingredients_number: 2, dependents: 0, production_time: 0.865)
Product.create(sku: '41', description: 'Suero de Leche', _type: 'Producto procesado', creator: 2, unit: 'Lts', unit_production_cost: 256, batch: 200, ingredients_number: 1, dependents: 2, production_time: 1.687)
Product.create(sku: '41', description: 'Suero de Leche', _type: 'Producto procesado', creator: 3, unit: 'Lts', unit_production_cost: 256, batch: 200, ingredients_number: 1, dependents: 2, production_time: 1.46)
Product.create(sku: '41', description: 'Suero de Leche', _type: 'Producto procesado', creator: 7, unit: 'Lts', unit_production_cost: 256, batch: 200, ingredients_number: 1, dependents: 2, production_time: 2.091)
Product.create(sku: '42', description: 'Cereal Maíz', _type: 'Producto procesado', creator: 8, unit: 'Kg', unit_production_cost: 812, batch: 200, ingredients_number: 3, dependents: 0, production_time: 2.743)
Product.create(sku: '46', description: 'Chocolate', _type: 'Producto procesado', creator: 1, unit: 'Kg', unit_production_cost: 424, batch: 800, ingredients_number: 3, dependents: 0, production_time: 1.848)
Product.create(sku: '47', description: 'Vino ', _type: 'Producto procesado', creator: 7, unit: 'Lts', unit_production_cost: 550, batch: 1000, ingredients_number: 3, dependents: 0, production_time: 1.236)
Product.create(sku: '48', description: 'Pasta de Sémola ', _type: 'Producto procesado', creator: 3, unit: 'Kg', unit_production_cost: 786, batch: 500, ingredients_number: 3, dependents: 0, production_time: 1.665)
Product.create(sku: '49', description: 'Leche Descremada', _type: 'Producto procesado', creator: 1, unit: 'Lts', unit_production_cost: 268, batch: 200, ingredients_number: 1, dependents: 2, production_time: 2.046)
Product.create(sku: '49', description: 'Leche Descremada', _type: 'Producto procesado', creator: 2, unit: 'Lts', unit_production_cost: 268, batch: 200, ingredients_number: 1, dependents: 2, production_time: 2.368)
Product.create(sku: '49', description: 'Leche Descremada', _type: 'Producto procesado', creator: 3, unit: 'Lts', unit_production_cost: 268, batch: 200, ingredients_number: 1, dependents: 2, production_time: 1.846)
Product.create(sku: '50', description: 'Arroz con Leche', _type: 'Producto procesado', creator: 4, unit: 'Kg', unit_production_cost: 773, batch: 350, ingredients_number: 3, dependents: 0, production_time: 2.832)
Product.create(sku: '51', description: 'Pan Hallulla', _type: 'Producto procesado', creator: 7, unit: 'Kg', unit_production_cost: 948, batch: 600, ingredients_number: 4, dependents: 0, production_time: 3.061)
Product.create(sku: '52', description: 'Harina Integral', _type: 'Producto procesado', creator: 3, unit: 'Kg', unit_production_cost: 410, batch: 890, ingredients_number: 2, dependents: 2, production_time: 1.443)
Product.create(sku: '52', description: 'Harina Integral', _type: 'Producto procesado', creator: 5, unit: 'Kg', unit_production_cost: 410, batch: 890, ingredients_number: 2, dependents: 2, production_time: 1.506)
Product.create(sku: '52', description: 'Harina Integral', _type: 'Producto procesado', creator: 7, unit: 'Kg', unit_production_cost: 410, batch: 890, ingredients_number: 2, dependents: 2, production_time: 1.897)
Product.create(sku: '53', description: 'Pan Integral', _type: 'Producto procesado', creator: 8, unit: 'Kg', unit_production_cost: 934, batch: 620, ingredients_number: 5, dependents: 0, production_time: 2.4)
Product.create(sku: '54', description: 'Hamburguesas', _type: 'Producto procesado', creator: 4, unit: 'Kg', unit_production_cost: 606, batch: 1800, ingredients_number: 2, dependents: 0, production_time: 0.86)
Product.create(sku: '55', description: 'Galletas Integrales', _type: 'Producto procesado', creator: 4, unit: 'Kg', unit_production_cost: 925, batch: 950, ingredients_number: 4, dependents: 0, production_time: 3.283)
Product.create(sku: '56', description: 'Hamburguesas de Pollo', _type: 'Producto procesado', creator: 5, unit: 'Kg', unit_production_cost: 479, batch: 620, ingredients_number: 2, dependents: 0, production_time: 1.533)
Formula.create(sku: '4', description: 'Aceite de Maravilla', unit: 'Lts', ingredient_sku: '38', requirement: 190, ingredient_unit: 'Kg')
Formula.create(sku: '5', description: 'Yogur ', unit: 'Lts', ingredient_sku: '49', requirement: 228, ingredient_unit: 'Lts')
Formula.create(sku: '5', description: 'Yogur ', unit: 'Lts', ingredient_sku: '6', requirement: 228, ingredient_unit: 'Lts')
Formula.create(sku: '5', description: 'Yogur ', unit: 'Lts', ingredient_sku: '41', requirement: 194, ingredient_unit: 'Lts')
Formula.create(sku: '6', description: 'Crema', unit: 'Lts', ingredient_sku: '49', requirement: 100, ingredient_unit: 'Lts')
Formula.create(sku: '6', description: 'Crema', unit: 'Lts', ingredient_sku: '7', requirement: 300, ingredient_unit: 'Lts')
Formula.create(sku: '10', description: 'Pan Marraqueta', unit: 'Kg', ingredient_sku: '23', requirement: 342, ingredient_unit: 'Kg')
Formula.create(sku: '10', description: 'Pan Marraqueta', unit: 'Kg', ingredient_sku: '26', requirement: 309, ingredient_unit: 'Kg')
Formula.create(sku: '10', description: 'Pan Marraqueta', unit: 'Kg', ingredient_sku: '4', requirement: 100, ingredient_unit: 'Lts')
Formula.create(sku: '10', description: 'Pan Marraqueta', unit: 'Kg', ingredient_sku: '27', requirement: 279, ingredient_unit: 'Kg')
Formula.create(sku: '11', description: 'Margarina ', unit: 'Kg', ingredient_sku: '4', requirement: 828, ingredient_unit: 'Lts')
Formula.create(sku: '12', description: 'Cereal Avena ', unit: 'Kg', ingredient_sku: '25', requirement: 133, ingredient_unit: 'Kg')
Formula.create(sku: '12', description: 'Cereal Avena ', unit: 'Kg', ingredient_sku: '20', requirement: 147, ingredient_unit: 'Kg')
Formula.create(sku: '12', description: 'Cereal Avena ', unit: 'Kg', ingredient_sku: '15', requirement: 113, ingredient_unit: 'Kg')
Formula.create(sku: '16', description: 'Pasta de Trigo ', unit: 'Kg', ingredient_sku: '23', requirement: 330, ingredient_unit: 'Kg')
Formula.create(sku: '16', description: 'Pasta de Trigo ', unit: 'Kg', ingredient_sku: '26', requirement: 313, ingredient_unit: 'Kg')
Formula.create(sku: '16', description: 'Pasta de Trigo ', unit: 'Kg', ingredient_sku: '2', requirement: 383, ingredient_unit: 'Un')
Formula.create(sku: '17', description: 'Cereal Arroz ', unit: 'Kg', ingredient_sku: '25', requirement: 360, ingredient_unit: 'Kg')
Formula.create(sku: '17', description: 'Cereal Arroz ', unit: 'Kg', ingredient_sku: '20', requirement: 350, ingredient_unit: 'Kg')
Formula.create(sku: '17', description: 'Cereal Arroz ', unit: 'Kg', ingredient_sku: '13', requirement: 290, ingredient_unit: 'Kg')
Formula.create(sku: '18', description: 'Pastel ', unit: 'Un', ingredient_sku: '23', requirement: 72, ingredient_unit: 'Kg')
Formula.create(sku: '18', description: 'Pastel ', unit: 'Un', ingredient_sku: '2', requirement: 71, ingredient_unit: 'Un')
Formula.create(sku: '18', description: 'Pastel ', unit: 'Un', ingredient_sku: '7', requirement: 67, ingredient_unit: 'Lts')
Formula.create(sku: '22', description: 'Mantequilla ', unit: 'Kg', ingredient_sku: '6', requirement: 380, ingredient_unit: 'Lts')
Formula.create(sku: '23', description: 'Harina', unit: 'Kg', ingredient_sku: '8', requirement: 309, ingredient_unit: 'Kg')
Formula.create(sku: '34', description: 'Cerveza ', unit: 'Lts', ingredient_sku: '14', requirement: 333, ingredient_unit: 'Kg')
Formula.create(sku: '34', description: 'Cerveza ', unit: 'Lts', ingredient_sku: '27', requirement: 319, ingredient_unit: 'Kg')
Formula.create(sku: '40', description: 'Queso ', unit: 'Kg', ingredient_sku: '7', requirement: 1000, ingredient_unit: 'Lts')
Formula.create(sku: '40', description: 'Queso ', unit: 'Kg', ingredient_sku: '41', requirement: 800, ingredient_unit: 'Lts')
Formula.create(sku: '41', description: 'Suero de Leche', unit: 'Lts', ingredient_sku: '7', requirement: 2000, ingredient_unit: 'Lts')
Formula.create(sku: '42', description: 'Cereal Maíz', unit: 'Kg', ingredient_sku: '25', requirement: 67, ingredient_unit: 'Kg')
Formula.create(sku: '42', description: 'Cereal Maíz', unit: 'Kg', ingredient_sku: '20', requirement: 71, ingredient_unit: 'Kg')
Formula.create(sku: '42', description: 'Cereal Maíz', unit: 'Kg', ingredient_sku: '3', requirement: 69, ingredient_unit: 'Kg')
Formula.create(sku: '46', description: 'Chocolate', unit: 'Kg', ingredient_sku: '20', requirement: 296, ingredient_unit: 'Kg')
Formula.create(sku: '46', description: 'Chocolate', unit: 'Kg', ingredient_sku: '25', requirement: 269, ingredient_unit: 'Kg')
Formula.create(sku: '46', description: 'Chocolate', unit: 'Kg', ingredient_sku: '7', requirement: 251, ingredient_unit: 'Lts')
Formula.create(sku: '47', description: 'Vino ', unit: 'Lts', ingredient_sku: '39', requirement: 495, ingredient_unit: 'Kg')
Formula.create(sku: '47', description: 'Vino ', unit: 'Lts', ingredient_sku: '27', requirement: 570, ingredient_unit: 'Kg')
Formula.create(sku: '47', description: 'Vino ', unit: 'Lts', ingredient_sku: '25', requirement: 1000, ingredient_unit: 'Kg')
Formula.create(sku: '48', description: 'Pasta de Sémola ', unit: 'Kg', ingredient_sku: '19', requirement: 160, ingredient_unit: 'Kg')
Formula.create(sku: '48', description: 'Pasta de Sémola ', unit: 'Kg', ingredient_sku: '26', requirement: 172, ingredient_unit: 'Kg')
Formula.create(sku: '48', description: 'Pasta de Sémola ', unit: 'Kg', ingredient_sku: '2', requirement: 155, ingredient_unit: 'Un')
Formula.create(sku: '49', description: 'Leche Descremada', unit: 'Lts', ingredient_sku: '7', requirement: 222, ingredient_unit: 'Lts')
Formula.create(sku: '50', description: 'Arroz con Leche', unit: 'Kg', ingredient_sku: '7', requirement: 200, ingredient_unit: 'Lts')
Formula.create(sku: '50', description: 'Arroz con Leche', unit: 'Kg', ingredient_sku: '25', requirement: 41, ingredient_unit: 'Kg')
Formula.create(sku: '50', description: 'Arroz con Leche', unit: 'Kg', ingredient_sku: '13', requirement: 100, ingredient_unit: 'Kg')
Formula.create(sku: '51', description: 'Pan Hallulla', unit: 'Kg', ingredient_sku: '23', requirement: 800, ingredient_unit: 'Kg')
Formula.create(sku: '51', description: 'Pan Hallulla', unit: 'Kg', ingredient_sku: '26', requirement: 182, ingredient_unit: 'Kg')
Formula.create(sku: '51', description: 'Pan Hallulla', unit: 'Kg', ingredient_sku: '22', requirement: 200, ingredient_unit: 'Kg')
Formula.create(sku: '51', description: 'Pan Hallulla', unit: 'Kg', ingredient_sku: '27', requirement: 279, ingredient_unit: 'Kg')
Formula.create(sku: '52', description: 'Harina Integral', unit: 'Kg', ingredient_sku: '8', requirement: 1000, ingredient_unit: 'Kg')
Formula.create(sku: '52', description: 'Harina Integral', unit: 'Kg', ingredient_sku: '38', requirement: 20, ingredient_unit: 'Kg')
Formula.create(sku: '53', description: 'Pan Integral', unit: 'Kg', ingredient_sku: '52', requirement: 500, ingredient_unit: 'Kg')
Formula.create(sku: '53', description: 'Pan Integral', unit: 'Kg', ingredient_sku: '26', requirement: 63, ingredient_unit: 'Kg')
Formula.create(sku: '53', description: 'Pan Integral', unit: 'Kg', ingredient_sku: '38', requirement: 250, ingredient_unit: 'Kg')
Formula.create(sku: '53', description: 'Pan Integral', unit: 'Kg', ingredient_sku: '7', requirement: 651, ingredient_unit: 'Lts')
Formula.create(sku: '53', description: 'Pan Integral', unit: 'Kg', ingredient_sku: '23', requirement: 15, ingredient_unit: 'Kg')
Formula.create(sku: '54', description: 'Hamburguesas', unit: 'Kg', ingredient_sku: '9', requirement: 2154, ingredient_unit: 'Kg')
Formula.create(sku: '54', description: 'Hamburguesas', unit: 'Kg', ingredient_sku: '26', requirement: 153, ingredient_unit: 'Kg')
Formula.create(sku: '55', description: 'Galletas Integrales', unit: 'Kg', ingredient_sku: '52', requirement: 1365, ingredient_unit: 'Kg')
Formula.create(sku: '55', description: 'Galletas Integrales', unit: 'Kg', ingredient_sku: '20', requirement: 96, ingredient_unit: 'Kg')
Formula.create(sku: '55', description: 'Galletas Integrales', unit: 'Kg', ingredient_sku: '23', requirement: 20, ingredient_unit: 'Kg')
Formula.create(sku: '55', description: 'Galletas Integrales', unit: 'Kg', ingredient_sku: '2', requirement: 560, ingredient_unit: 'Un')
Formula.create(sku: '56', description: 'Hamburguesas de Pollo', unit: 'Kg', ingredient_sku: '1', requirement: 935, ingredient_unit: 'Kg')
Formula.create(sku: '56', description: 'Hamburguesas de Pollo', unit: 'Kg', ingredient_sku: '26', requirement: 65, ingredient_unit: 'Kg')

Spree::Core::Engine.load_seed if defined?(Spree::Core)
Spree::Auth::Engine.load_seed if defined?(Spree::Auth)
